enso-org/enso

syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs
syntax/text/parser/test/spec/Luna/Test/Source/Text/ParserSpec.hs

For caseless scripts (like korean or chinese) you need to prepend variable name with some lowercase letter or `_`:
```
def main:
_김동욱 = "Hello, World!"
```

Allow unicode symbols in variable names #96

---

core/package.yaml
core/src-libs/Luna/Test/IR/Runner.hs
core/src/OCI/IR/Repr/Vis.hs

This changes how IR vis is used.
Before we were putting the graph description straight into the URL. This broke on any graph larger than a dozen nodes.
Now the visualizer puts the data in a file (in a location specified as a value of the `DEBUGVIS` variable, about which contents we didn't care before) and passes the name of this file in the URL. This is accompanied by this PR in IRVis: https://github.com/luna/irvis/pull/1

Make visualizations work with arbitrary-sized graphs

---

stdlib/Std/src/Base.luna
stdlib/src/Luna/Prim/Base.hs

Another round of adding what has been found missing by the users.
In this episode:
– the `>=` and `<=` operators work by delegating to `<` and `==`, allowing new classes not to implement them (and adds them on `Time` objects in the process)
– `List` gets a `last` method.

Add missing stdlib functions

---

project/package.yaml
project/src/Luna/Project.hs
shell/src/Luna/Shell.hs

This solution is not ideal, because you can directly import your indirect dependencies. Please tell if that's unacceptable

Resolve local dependencies from local_libs directory

---

stdlib/Std/src/HTTP.luna

Previous version did not compile due to an obvious mistake.

Fix the definition of HTTP HEAD method.

---

stdlib/Std/src/Base.luna
stdlib/src/Luna/Prim/Base.hs

Because some endpoints require integers to be rendered as integers.

Use Scientific instead of Real inside JSONs

---

stack.yaml

The `stack.yaml` is now a level higher, and the current version puts luna outside of the repository.

Fix local bin path

---

project/src/Luna/Compilation.hs
project/src/Luna/Project.hs
shell/src/Luna/Shell.hs

Probably the biggest change here is that assignQualName always includes the project name in the qualified name, that simplifies handling these names in Luna Studio. Also, LUNA_HOME env variable is unified with Luna Studi and changed to LUNA_LIBS_PATH

Proper resolution of projects in local_libs

---

core/src-libs/Data/Event.hs
core/src-libs/Data/Graph/Class.hs
passes/src/Luna/Pass/Inference/StructuralTyping.hs
passes/src/Luna/Pass/Resolution/ConstructorResolution.hs
passes/src/Luna/Pass/Resolution/Data/ImportError.hs
passes/src/Luna/Pass/Resolution/DeconstructorResolution.hs

This fixes some silent modes of failure for malformed pattern matches, in particular #194 .
The pattern match cases that start throwing errors are caused by:
1. Using an undefined constructor in pattern;
2. Defining branches matching on constructors of different types;
3. Applying the constructor in pattern to too small a number of arguments.
The following functions did not report a compile error when they should (resulting in either runtime crashes or accidentally working) and they do report an error now:
```
def test1:
case Just 5 of
Jsut 5: 5
def test2:
case Just 5 of
20: 0
Left foo: foo
Just x: x
def test3:
case Just 5 of
Just: 20
```

Report errors for malformed pattern matches

---

stdlib/Std/src/System.luna
stdlib/src/Luna/Prim/System.hs

Adding two functions:
* `System.lookupEnv` which is a parallel of Haskell's `System.Environment.lookupEnv`
* `System.getEnv` which is a parallel of Haskell's `System.Environment.getEnv`

[stdlib] Fetching environment variables

---

package/src/Luna/Package.hs

An unused default value in `Package.hs` meant that a TH splice wouldn't compile on windows. This PR instead uses the current directory as a default.
Fixes #276.

Fix compilation issue on windows

---

passes/src/Luna/Pass/Sourcing/ClassProcessor.hs
stdlib/StdTest/src/Lang/ToJSONGeneration.luna
stdlib/StdTest/src/Main.luna

Generate default toJSON method for classes without it.
Notable change: Luna classes have automatically derived `toJSON` method if not specified.

Generate default toJSON implementation for classes

---

passes/src/Luna/Pass/Data/Error.hs
passes/src/Luna/Pass/Resolve/ConsResolution.hs
passes/src/Luna/Pass/Sourcing/ClassProcessor.hs
passes/src/Luna/Pass/Sourcing/UnitMapper.hs

This pull request introduces errors for most of duplicate definition scenarios, with one exception. Namely, whenever we have two class definitions without explicit constructors, errors won't be shown at callsite. I'm not sure why is this happening, I tried to set error on Record node, but it seems to be unused for constructor resolution. @kustosz if you could help here, I would greatly appreciate it.
Error messages are subject to change if you have any improvement requests.

Report errors for duplicate definitions

---

stdlib/src/Luna/Prim/Base.hs

Fix arguments list for builtin functions Std.Base.Binary.take and drop.
Fixes https://github.com/luna/luna-studio/issues/1029.
Please note I wasn't able to test this, as I don't have access to a machine with enough RAM to successfully compile Luna.

fix Std.Base.Binary.take & .drop

---

syntax/text/parser2/src/Luna/Syntax/Text/Parser/Ast/Spanned.hs
syntax/text/parser2/src/Luna/Syntax/Text/Parser/Parser/Class.hs

Fixes issue with docstrings containing only the first line.

Include all comments in a docstring instead of only the first line

---

stdlib/Std/src/Base.luna
stdlib/Std/src/Time.luna

This PR adds support for a new LQuery type: timestamp (stored as ns count since unix epoch start) and conversion from Luna' `Time` type. It is accompanied by a few methods for date components extraction.
In future some improvements should be made:
* support other time units besides nanoseconds
* `Time` is exactly equivalent to Arrow's timestamp (different resolution + time zone)

Standard library parts of LQuery support for Arrow's Timestamp datatype.

---

package/src/Luna/Package.hs
stdlib/package.yaml
stdlib/src/Luna/Prim/DynamicLinker.hs

This pull request causes Luna to treat all projects located at LUNA_LIBS_PATH as available to import. It was done to prepare a package with Dataframes embedded and seems to work as intended on Windows.
Projects discovery is rather simple, treating all directories starting with capital letter as Luna projects.

Treat all projects in LUNA_LIBS_PATH as available to import

---

syntax/text/parser3/src/Luna/Pass/Parsing/Parser.hs
syntax/text/parser3/test/spec/Luna/Test/Source/Text/ParserSpec.hs

Restore previous behaviour in regard to parsing AccSections as defined in #301 

Hack previous parser behaviour for AccSection

---

package/src/Luna/Package.hs
package/src/Luna/Package/Utilities.hs
package/test/spec/Luna/PackageSpec.hs
shell/src/Luna/Shell/Command.hs
shell/src/Luna/Shell/Option.hs

This PR fixes #303, and the error reported in [luna-studio/#1025](https://github.com/luna/luna-studio/issues/1025). It also introduces a command-line `rename` command that utilises the same functionality. 
- The bugfix changed a 'move' operation to a 'copy' operation to work across device boundaries. 
- The new command simply accepts a source and destination project name. 

Fix Package Renaming + Add Rename Command

---

config/snapshot-local.yaml
config/snapshot.yaml
package/test/spec/Luna/Package/Configuration/GlobalSpec.hs

Bump the stackage snapshot. Currently limited to `lts-12.16` due to dependencies not being updated enough yet.

Bump Stackage Snapshot

---

config/snapshot.yaml
package/src/Luna/Package.hs
package/src/Luna/Package/Structure/Generate/Internal.hs
package/test/spec/Luna/PackageSpec.hs
shell/src/Luna/Shell/Command.hs

The rename functionality was relying on the existence of a pre-existing `config.yaml` in the package structure. This was a change from the very first Luna package format, but the renamer wasn't taking that into account. It now generates a stub config file if it is missing when renaming a package.

Generate Package Config if Missing for Backwards Compat

---

stdlib/Std/src/Base.luna

Duplicate definition of toBinary in JSON class prevents conversion of JSON to Binary
Nothing changed in API

Remove duplicate toBinary method in JSON class

---

package/src/Luna/Package.hs
package/test/spec/Luna/PackageSpec.hs
shell/src/Luna/Shell/Command.hs

Change the error behaviour of the `Luna.Package.rename` function so that it doesn't throw an exception if it encounters an inability to remove the original directory. The error is instead bubbled up through the return value so that it can be logged.
This aims to help with [#1254](https://github.com/luna/luna-studio/issues/1254).

Change error behaviour of rename

---

stdlib/src/Luna/Prim/DynamicLinker.hs

Fixes erroneous behaviour when missing `ldconfig` would cause foreign function linking failure. If executing `ldconfig` results in an exception, it is ignored.

Ignore exceptions thrown by running ldconfig during linking

---

stdlib/src/Luna/Prim/DynamicLinker.hs

Stray fmap caused found directories to be glued

Fix searching for native libs directories

---

.circleci/config.yml
.circleci/luna-ci/Dockerfile
stdlib/StdTest/src/Main.luna

This PR makes the CI builds succeed by fixing some issues and avoiding others. If all commits are reported to fail, then we have no useful information whatsoever.
There were actually a few problems:
* Docker image didn't have GCC-7 — I solved this by creating a new image with current GCC-8 installed
* running tests of standard library always failed because of parser issues (see discussion in https://github.com/luna/luna/pull/299 )
* even if problematic tests were ommitted, they still timed out — I've explicitly increased the timeout limit for the tests command (unoptimized build of luna is slow)
A separate issue shall be created for the failing tests problem.

Fix the CI build status

---

lib/exception/src/Control/Monad/Exception.hs

This PR brings `fromRight` and `fromRight'` to the `luna-exception` package from its alternate incarnation at https://github.com/luna/luna-manager/blob/39d0c1279aea5315b403eb1734132eb4eea472b4/luna-manager/src/Control/Monad/Raise.hs#L95
I've only updated names to follow the new `fromSth` naming convention.
These function are used in the luna-manager codebase.

Added fromRight and fromRight' fucntions.

---

stdlib/Std/src/Base.luna
stdlib/StdTest/src/Lib/Basic.luna

1. `Real.abs` didn't work because self couldn't be compared against Integer literal 0.
2. `Complex.modulus` returned modulus squared. I have added sqrt call, and `modulusSquared` method for previous behaviour.

Real.abs and Comples.modulus

---

.ci/azure-pipelines.yml

Currently CI runs twice on pull requests to this repo due to overlapping triggers. This is an attempt to prevent this from happening. 

Prevent CI running twice on Pull Requests

---

package/src/Luna/Package/Env.hs
package/src/Luna/Package/Environment.hs
shell/src/Luna/Shell/Interpret.hs
stdlib/Std/src/Base.luna
stdlib/src/Luna/Prim/Package.hs
stdlib/src/Luna/Std.hs
syntax/text/parser/src/Luna/Syntax/Text/Parser/Hardcoded.hs

This introduces a way for Luna code to peek into the files exposed by available libraries. It is needed for providing sample data to libraries, making it easier for users to try out different capabilities.
The implementation exports specific environment variables during evaluation of Luna code.
For a package named `ExamplePackage`, there will appear a `LUNA_LIBRARY_EXAMPLE_PACKAGE` environment variable, set to the absolute location of the root of `ExamplePackage`.
There's also a Luna helper allowing to access these without thinking about env vars:
```
Package.root 'ExamplePackage' # returns the absolute path to ExamplePackage
Package.samples 'ExamplePackage' # returns the absolute path to `samples` subdirectory of ExamplePackage
```
This allows to access samples e.g. like this:
``` …
```

Library env vars

---

.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docs.yml
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/distribution/README.md
docs/getting-enso.md
docs/infrastructure/java-11.md
docs/rfcs/README.md
docs/runtime/runtime-features.md
docs/style-guide/haskell.md
engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/io/InputOutputApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/monitoring/MonitoringApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/ErrorApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
lib/project-manager/src/main/resources/application.conf
lib/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
lib/project-manager/src/test/resources/application.conf
lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
parser/flexer/Cargo.toml
tools/performance/comparative-benchmark/benchmarks/haskell/package.yaml

This PR updates the enso repo to stop referring to "luna" and use "enso" instead. 

Update References to Luna to be Enso
