enso-org/enso

README.md

Is this what is intended? The previous sentence seemed self-contradictory

Suggested clarification about compiler options

---

README.md

As mentioned in Issue #89 [here](https://github.com/luna/luna/pull/89#issuecomment-359168189), I had slightly misunderstood the sentence. So @pmlodawski and I came up with a sentence that is both correct and clear, which is included here.
Sorry for the confusion!

Update README: Add clarification from discussion with @pmlodawski

---

passes/src/Luna/Pass/Resolution/MethodResolution.hs

This fixes a rather nasty bug that caused the typechecker to forget to resolve some assumptions. Any carry-over method assumption appearing during method importing was immediately dropped from the solver queue.

Fix overwriting accessors queue

---

stdlib/Std/src/Base.luna
stdlib/Std/src/Graphics2D.luna
stdlib/Std/src/System.luna
stdlib/Std/src/Time.luna
stdlib/src/Luna/Builtin/Std.hs

This is a rather unstructured portion of improvements that occured to me over using Luna the past few days. Among other things:
1. Adds ways to convert a real to an int
2. Adds some other missing functions for List and JSON
3. Adds some missing `shortRep`s and `toJSON`s
4. Declutters some `toJSON` instances by using the new API.

Stdlib improvements

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Added:
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
Modified:
- README.md: Added section on contributing with link. Reformatted the build instructions.

Contributor Guidelines

---

CONTRIBUTING.md
README.md

Fixed typo in README and CONTRIBUTING. Formatted links.

Readme Fixes

---

stdlib/Std/src/HTTP.luna

Add PATCH support to HTTP client

---

stdlib/Std/src/HTTP.luna

Add OPTIONS support to HTTP client

---

stdlib/Std/src/HTTP.luna

Add HEAD support to HTTP client

---

stdlib/Std/src/HTTP.luna

Add TRACE support to HTTP client

---

stdlib/Std/src/HTTP.luna

Add CONNECT support to HTTP client

---

core/src-libs/Luna/Test/Utils.hs
core/src/Luna/IR/Analysis.hs
core/src/Luna/IR/ToRefactor.hs
core/src/OCI/IR/Combinators.hs
core/src/OCI/Pass/Definition.hs
stdlib/src/Luna/Prim/Time.hs
stdlib/src/Luna/Std/Builder.hs

The only remaining warning at this time is for readTerm.

Fixes deprecation warnings

---

stdlib/Std/src/WebSockets.luna

Current version does not compile

Update Text API in WebSockets client

---

stdlib/Std/src/Base.luna

Enables using JSON objects as HTTP request bodies, which I'd say is pretty handy.

Add toBinary method on JSON

---

stdlib/Std/src/HTTP.luna
stdlib/src/Luna/Prim/HTTP.hs

They are sometimes quite useful... :)

Add a way to access HTTP response headers

---

syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs
syntax/text/parser/src/Luna/Syntax/Text/Pretty/Pretty.hs
syntax/text/parser/test/spec/Luna/Test/Source/Text/ParserSpec.hs

This PR implements the comment character swap as proposed and accepted in the [Comments Overhaul RFC](https://github.com/luna/luna-rfcs/blob/master/text/0001-comments-overhaul.md).

Comment Overhaul

---

stdlib/Std/src/Foreign/C/Value.luna

Manually dealing with this kind of data started to annoy me, so I guess it should have an automated flow.

Add helper class for dealing with C arrays

---

stdlib/Std/src/Base.luna

And fix the docs for safe casting functions.

Add int accessors for JSON objects

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/task.md
.github/PULL_REQUEST_TEMPLATE.md
config/snapshot.yaml
shell/package.yaml
shell/src-app/Main.hs
shell/src/Luna/Shell/Command.hs
shell/src/Luna/Shell/Option.hs

This PR creates templates for pull-requests and issues, as well as adding a `luna --version` command to help with bug reports.

Create PR and Issue Templates

---

shell/src/Luna/Shell/Command.hs

The information provided by the `--version` flag was incomplete with regards to the specification. It also lacked some information that would be useful when attempting to reproduce bugs. This PR adds that information.

Add additional debug info to `--version` flag.

---

stdlib/Std/src/WebSockets.luna

It was the first time I'm trying out Luna and I tried some WebSocket basics, and noticed how the library fails when I'm adding a path, so I noticed the source code is not coded to accept paths.

A temporary fix for the WS library

---

passes/src/Luna/Pass/Evaluation/Interpreter.hs

I believe that this pull request fixes the reason of luna/luna-studio#1088 that was introduced with interpreting anonymous nodes.

Fix side effects in interpreter

---

.circleci/config.yml
shell/src/Luna/Shell/Command.hs

We have some tests for Luna and CI should run them.

Run tests after build

---

package/src/Luna/Package/Structure/Generate/Internal.hs

- This PR removes initial "Test me" node, added to empty project. We are removing it, because we are going to display message "press TAB to start" when there are no nodes on scene 

Remove "test me" initial node.

---

package/src/Luna/Package/Structure/Generate.hs
package/src/Luna/Package/Structure/Generate/Internal.hs

Minor refactoring to Luna.Package.Generate.

---

package/src/Luna/Package.hs
shell/package.yaml
shell/src/Luna/Shell/Command.hs

Quick hack to make rename not error on windows.

---

config/snapshot.yaml

Fix dependencies for Luna in prepration for GHC-8.6

---

config/hpack-common.yaml
lib/layered-state/src/Control/Monad/State/Layered.hs

This instance is required to aid migration away from `MonadCatch` in Luna Manager.

State monad catch

---

lib/exception/src/Control/Monad/Exception/IO.hs

- Please describe the nature of your PR here, as well as the motivation for it.
- If it fixes an open issue, please mention that issue number here. 
- Mention important elements of the design.
- Mention any notable changes to APIs. 

Rethrow All Utility

---

lib/datafile/src/Luna/Datafile.hs
lib/datafile/src/Luna/Datafile/Licenses.hs
lib/datafile/src/Luna/Datafile/Stdlib.hs

This PR adds a detailed walkthrough of the stdlib example for this library to better illustrate how its used and why it's designed how it is. 

Document the luna-datafile Library

---

README.md

Add CI status to the Luna readme. 

Add CI status icons to the Luna readme

---

shell/package.yaml

The project was not building on my machine. With this change it does.

add a CC flag for macOS cabal paths

---

shell/src/Luna/Shell/Interpret.hs

CLI will exit with a non-zero code on compile errors
I mean... see the diff.

Cli exit failure

---

stdlib/Std/snippets.yaml

Code snippets to work with Luna Studio searcher.

code snippets

---

passes/src/Luna/Pass/Evaluation/EvaluateUnits.hs
passes/src/Luna/Pass/Flow/ProcessUnits.hs
passes/src/Luna/Pass/Preprocess/PreprocessUnit.hs
passes/src/Luna/Pass/Sourcing/ClassProcessor.hs
passes/src/Luna/Pass/Sourcing/Data/Def.hs
passes/src/Luna/Pass/Sourcing/UnitMapper.hs
passes/src/Luna/Pass/Typing/TypeUnits.hs

This preserves information about definition order for definitions and methods. Needed downstream by the node searcher.
Nothing of interest changes, we just memorize the required information.

Add definition order to functions

---

.ci/azure-pipelines.yml
CONTRIBUTING.md

This is a paragraph gathering issues for community possible contributions. 

Add a paragraph `Issues` to Luna contributing guidelines

---

config/snapshot.yaml
lib/datafile/package.yaml
lib/datafile/src/Luna/Datafile.hs
lib/datafile/test/spec/Luna/DatafileSpec.hs
package/package.yaml
package/src/Luna/Package.hs
package/src/Luna/Package/Configuration/Global.hs
package/src/Luna/Package/Configuration/License/Data.hs
package/src/Luna/Package/Environment.hs
package/src/Luna/Package/Orphans.hs
package/src/Luna/Package/Structure/Generate.hs
package/src/Luna/Package/Structure/Generate/Internal.hs
package/src/Luna/Package/Structure/Name.hs
package/src/Luna/Package/Structure/Utilities.hs
package/src/Luna/Package/Utilities.hs
package/test/spec/Luna/Package/Structure/GenerateSpec.hs
package/test/spec/Luna/PackageSpec.hs
passes/package.yaml
passes/src/Luna/Pass/Sourcing/UnitLoader.hs
path/package.yaml
path/src/Luna/Path.hs
path/src/Luna/Path/Path.hs
shell/package.yaml
shell/src/Luna/Shell/CWD.hs
shell/src/Luna/Shell/Command.hs
shell/src/Luna/Shell/GenerateDocumentation.hs
shell/src/Luna/Shell/Interpret.hs
stack.yaml
stdlib/package.yaml
stdlib/src/Luna/Prim/DynamicLinker.hs

Make use of Path/Path.IO as much as possible. See Issue:https://github.com/luna/luna/issues/404
Please, look at the TODO [JCM]. These are open questions/proposals.
I created a new package: luna-path which contains functions not available in the path package.

Make use of Path/Path.IO as much as possible

---

.github/workflows/docs.yml
.github/workflows/scala.yml

Update CI Secret Names
